export const CITIES = [
  'Jerusalem',
  'Tel Aviv',
  'Haifa',
  'Rishon LeZion',
  'Petah Tikva',
  'Ashdod',
  'Netanya',
  'Beersheba',
  'Bnei Brak',
  'Holon',
  'Ramat Gan',
  'Ashkelon',
  'Rehovot',
  'Bat Yam',
  'Beit Shemesh',
  'Kfar Saba',
  'Herzliya',
  'Hadera',
  'Modiin-Maccabim-Reut',
  'Nazareth',
  'Lod',
  'Ramla',
  'Raanana',
  'Rosh HaAyin',
  'Acre (Akko)',
  'Eilat',
  'Kiryat Ata',
  'Kiryat Gat',
  'Kiryat Yam',
  'Kiryat Motzkin',
  'Kiryat Bialik',
  'Nahariya',
  'Givatayim',
  'Hod HaSharon',
  'Umm al-Fahm',
  'Tiberias',
  'Karmiel',
  'Or Yehuda',
  'Ramat HaSharon',
  'Maale Adumim',
  `Giv'at Shmuel`,
  'Tamra',
  'Sakhnin',
  'Migdal HaEmek',
  'Tira',
  'Yavne',
  'Safed (Tzfat)',
  'Dimona',
  'Netivot',
  'Ofakim',
  'Sderot',
  'Arad',
  'Kiryat Shmona',
  'Yehud-Monosson',
  `Giv'at Ze'ev`,
  'Nesher',
  'Shoham',
  'Tirat Carmel',
];
